#version: '3'
services:
  # Servicio para Laravel (Backend)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: thiio
      DB_USERNAME: thiio
      DB_PASSWORD: thiio

  # Servicio para Vue.js (Frontend)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:80"

  # Servicio de base de datos
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: thiio
      MYSQL_ROOT_PASSWORD: thiio
      MYSQL_PASSWORD: thiio
      MYSQL_USER: thiio
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: